<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Vehicle;
use App\Models\VehicleImage;

class RentalFleetSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $vehicles = [
            // 🚘 SEDANS - All with proper specific images
            [
                'make' => 'Mercedes-Benz',
                'model' => 'E-Class',
                'year' => 2024,
                'category' => 'sedan',
                'color' => 'Black',
                'license_plate' => 'MBE-2024',
                'mileage' => 5000,
                'fuel_type' => 'petrol',
                'transmission' => 'automatic',
                'description' => 'Luxury sedan with premium comfort and advanced technology features.',
                'features' => ['leather_seats', 'sunroof', 'navigation', 'bluetooth', 'backup_camera', 'heated_seats', 'premium_sound'],
                'available_for_rent' => true,
                'rental_price_per_day' => 150.00,
                'self_drive_available' => true,
                'with_driver_available' => true,
                'driver_cost_per_day' => 80.00,
                'available_for_sale' => false,
                'status' => 'available',
                'condition' => 'excellent',
                'image_url' => 'https://images.unsplash.com/photo-1563720223185-11003d516935?w=800&auto=format&fit=crop&q=60'
            ],
            [
                'make' => 'Toyota',
                'model' => 'Camry',
                'year' => 2023,
                'category' => 'sedan',
                'color' => 'Silver',
                'license_plate' => 'TOY-2023',
                'mileage' => 15000,
                'fuel_type' => 'petrol',
                'transmission' => 'automatic',
                'description' => 'Reliable midsize sedan perfect for business and family trips.',
                'features' => ['bluetooth', 'backup_camera', 'cruise_control', 'keyless_entry', 'power_windows'],
                'available_for_rent' => true,
                'rental_price_per_day' => 65.00,
                'self_drive_available' => true,
                'with_driver_available' => true,
                'driver_cost_per_day' => 60.00,
                'available_for_sale' => false,
                'status' => 'available',
                'condition' => 'excellent',
                'image_url' => 'https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=800&auto=format&fit=crop&q=60'
            ],
            [
                'make' => 'Honda',
                'model' => 'Accord',
                'year' => 2023,
                'category' => 'sedan',
                'color' => 'White',
                'license_plate' => 'HON-2023',
                'mileage' => 12000,
                'fuel_type' => 'petrol',
                'transmission' => 'automatic',
                'description' => 'Spacious midsize sedan with excellent fuel economy and comfort.',
                'features' => ['bluetooth', 'backup_camera', 'cruise_control', 'keyless_entry', 'power_seats'],
                'available_for_rent' => true,
                'rental_price_per_day' => 70.00,
                'self_drive_available' => true,
                'with_driver_available' => true,
                'driver_cost_per_day' => 60.00,
                'available_for_sale' => false,
                'status' => 'available',
                'condition' => 'excellent',
                'image_url' => 'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800&auto=format&fit=crop&q=60'
            ],
            [
                'make' => 'Honda',
                'model' => 'Civic',
                'year' => 2024,
                'category' => 'sedan',
                'color' => 'Blue',
                'license_plate' => 'CIV-2024',
                'mileage' => 8000,
                'fuel_type' => 'petrol',
                'transmission' => 'automatic',
                'description' => 'Compact sedan with modern design and excellent fuel efficiency.',
                'features' => ['bluetooth', 'backup_camera', 'cruise_control', 'keyless_entry', 'apple_carplay'],
                'available_for_rent' => true,
                'rental_price_per_day' => 55.00,
                'self_drive_available' => true,
                'with_driver_available' => true,
                'driver_cost_per_day' => 50.00,
                'available_for_sale' => false,
                'status' => 'available',
                'condition' => 'excellent',
                'image_url' => 'https://images.unsplash.com/photo-1619767886558-efdc259cde1a?w=800&auto=format&fit=crop&q=60'
            ],
            [
                'make' => 'Hyundai',
                'model' => 'Elantra',
                'year' => 2022,
                'category' => 'sedan',
                'color' => 'Red',
                'license_plate' => 'HYU-2022',
                'mileage' => 25000,
                'fuel_type' => 'petrol',
                'transmission' => 'automatic',
                'description' => 'Stylish compact sedan with great value and modern features.',
                'features' => ['bluetooth', 'backup_camera', 'cruise_control', 'keyless_entry', 'wireless_charging'],
                'available_for_rent' => true,
                'rental_price_per_day' => 50.00,
                'self_drive_available' => true,
                'with_driver_available' => true,
                'driver_cost_per_day' => 50.00,
                'available_for_sale' => false,
                'status' => 'available',
                'condition' => 'good',
                'image_url' => 'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800&auto=format&fit=crop&q=60'
            ],
            [
                'make' => 'Nissan',
                'model' => 'Altima',
                'year' => 2023,
                'category' => 'sedan',
                'color' => 'Gray',
                'license_plate' => 'NIS-2023',
                'mileage' => 18000,
                'fuel_type' => 'petrol',
                'transmission' => 'automatic',
                'description' => 'Comfortable midsize sedan with advanced safety features.',
                'features' => ['bluetooth', 'backup_camera', 'cruise_control', 'keyless_entry', 'blind_spot_monitoring'],
                'available_for_rent' => true,
                'rental_price_per_day' => 60.00,
                'self_drive_available' => true,
                'with_driver_available' => true,
                'driver_cost_per_day' => 55.00,
                'available_for_sale' => false,
                'status' => 'available',
                'condition' => 'excellent',
                'image_url' => 'https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?w=800&auto=format&fit=crop&q=60'
            ],
            [
                'make' => 'Toyota',
                'model' => 'Corolla',
                'year' => 2025,
                'category' => 'sedan',
                'color' => 'White',
                'license_plate' => 'COR-2025',
                'mileage' => 2000,
                'fuel_type' => 'petrol',
                'transmission' => 'automatic',
                'description' => 'Brand new compact sedan with latest technology and excellent fuel economy.',
                'features' => ['bluetooth', 'backup_camera', 'cruise_control', 'keyless_entry', 'apple_carplay', 'android_auto'],
                'available_for_rent' => true,
                'rental_price_per_day' => 58.00,
                'self_drive_available' => true,
                'with_driver_available' => true,
                'driver_cost_per_day' => 50.00,
                'available_for_sale' => false,
                'status' => 'available',
                'condition' => 'excellent',
                'image_url' => 'https://images.unsplash.com/photo-1623869675781-80aa31012a5a?w=800&auto=format&fit=crop&q=60'
            ],

            // 🚙 SUVs - All with proper SUV images
            [
                'make' => 'Honda',
                'model' => 'CR-V',
                'year' => 2022,
                'category' => 'suv',
                'color' => 'Black',
                'license_plate' => 'CRV-2022',
                'mileage' => 30000,
                'fuel_type' => 'petrol',
                'transmission' => 'automatic',
                'description' => 'Reliable compact SUV perfect for city driving and weekend adventures.',
                'features' => ['bluetooth', 'backup_camera', 'cruise_control', 'keyless_entry', 'all_wheel_drive', 'roof_rails'],
                'available_for_rent' => true,
                'rental_price_per_day' => 75.00,
                'self_drive_available' => true,
                'with_driver_available' => true,
                'driver_cost_per_day' => 65.00,
                'available_for_sale' => false,
                'status' => 'available',
                'condition' => 'good',
                'image_url' => 'https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=800&auto=format&fit=crop&q=60'
            ],
            [
                'make' => 'Toyota',
                'model' => 'RAV4',
                'year' => 2024,
                'category' => 'suv',
                'color' => 'Blue',
                'license_plate' => 'RAV-2024',
                'mileage' => 8000,
                'fuel_type' => 'petrol',
                'transmission' => 'automatic',
                'description' => 'Popular compact SUV with excellent reliability and off-road capability.',
                'features' => ['bluetooth', 'backup_camera', 'cruise_control', 'keyless_entry', 'all_wheel_drive', 'roof_rails', 'heated_seats'],
                'available_for_rent' => true,
                'rental_price_per_day' => 85.00,
                'self_drive_available' => true,
                'with_driver_available' => true,
                'driver_cost_per_day' => 70.00,
                'available_for_sale' => false,
                'status' => 'available',
                'condition' => 'excellent',
                'image_url' => 'https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=800&auto=format&fit=crop&q=60'
            ],
            [
                'make' => 'Ford',
                'model' => 'Explorer',
                'year' => 2023,
                'category' => 'suv',
                'color' => 'Silver',
                'license_plate' => 'EXP-2023',
                'mileage' => 20000,
                'fuel_type' => 'petrol',
                'transmission' => 'automatic',
                'description' => 'Spacious midsize SUV perfect for family trips and group travel.',
                'features' => ['bluetooth', 'backup_camera', 'cruise_control', 'keyless_entry', 'all_wheel_drive', 'third_row_seating', 'navigation'],
                'available_for_rent' => true,
                'rental_price_per_day' => 95.00,
                'self_drive_available' => true,
                'with_driver_available' => true,
                'driver_cost_per_day' => 75.00,
                'available_for_sale' => false,
                'status' => 'available',
                'condition' => 'excellent',
                'image_url' => 'https://images.unsplash.com/photo-1566473965997-3de9c817e938?w=800&auto=format&fit=crop&q=60'
            ],
            [
                'make' => 'Jeep',
                'model' => 'Wrangler',
                'year' => 2024,
                'category' => 'suv',
                'color' => 'Green',
                'license_plate' => 'JEP-2024',
                'mileage' => 12000,
                'fuel_type' => 'petrol',
                'transmission' => 'automatic',
                'description' => 'Iconic off-road SUV perfect for adventure seekers and outdoor enthusiasts.',
                'features' => ['bluetooth', 'backup_camera', 'cruise_control', 'keyless_entry', '4x4', 'removable_doors', 'off_road_tires'],
                'available_for_rent' => true,
                'rental_price_per_day' => 110.00,
                'self_drive_available' => true,
                'with_driver_available' => true,
                'driver_cost_per_day' => 80.00,
                'available_for_sale' => false,
                'status' => 'available',
                'condition' => 'excellent',
                'image_url' => 'https://images.unsplash.com/photo-1606016159991-8b5d2e5e4b8a?w=800&auto=format&fit=crop&q=60'
            ],
            [
                'make' => 'Chevrolet',
                'model' => 'Tahoe',
                'year' => 2023,
                'category' => 'suv',
                'color' => 'Black',
                'license_plate' => 'TAH-2023',
                'mileage' => 25000,
                'fuel_type' => 'petrol',
                'transmission' => 'automatic',
                'description' => 'Full-size SUV with maximum space and towing capacity for large groups.',
                'features' => ['bluetooth', 'backup_camera', 'cruise_control', 'keyless_entry', 'all_wheel_drive', 'third_row_seating', 'navigation', 'leather_seats'],
                'available_for_rent' => true,
                'rental_price_per_day' => 120.00,
                'self_drive_available' => true,
                'with_driver_available' => true,
                'driver_cost_per_day' => 90.00,
                'available_for_sale' => false,
                'status' => 'available',
                'condition' => 'excellent',
                'image_url' => 'https://images.unsplash.com/photo-1609521263047-f8f205293f24?w=800&auto=format&fit=crop&q=60'
            ],
            [
                'make' => 'Hyundai',
                'model' => 'Tucson',
                'year' => 2024,
                'category' => 'suv',
                'color' => 'White',
                'license_plate' => 'TUC-2024',
                'mileage' => 6000,
                'fuel_type' => 'petrol',
                'transmission' => 'automatic',
                'description' => 'Modern compact SUV with bold design and advanced technology.',
                'features' => ['bluetooth', 'backup_camera', 'cruise_control', 'keyless_entry', 'all_wheel_drive', 'wireless_charging', 'panoramic_sunroof'],
                'available_for_rent' => true,
                'rental_price_per_day' => 80.00,
                'self_drive_available' => true,
                'with_driver_available' => true,
                'driver_cost_per_day' => 65.00,
                'available_for_sale' => false,
                'status' => 'available',
                'condition' => 'excellent',
                'image_url' => 'https://images.unsplash.com/photo-1617788138017-80ad40651399?w=800&auto=format&fit=crop&q=60'
            ],

            // 🛻 TRUCKS - All with proper truck images
            [
                'make' => 'Ford',
                'model' => 'F-150',
                'year' => 2023,
                'category' => 'pickup',
                'color' => 'Blue',
                'license_plate' => 'F15-2023',
                'mileage' => 22000,
                'fuel_type' => 'petrol',
                'transmission' => 'automatic',
                'description' => 'America\'s best-selling truck with excellent towing capacity and durability.',
                'features' => ['bluetooth', 'backup_camera', 'cruise_control', 'keyless_entry', '4x4', 'tow_package', 'bed_liner'],
                'available_for_rent' => true,
                'rental_price_per_day' => 100.00,
                'self_drive_available' => true,
                'with_driver_available' => true,
                'driver_cost_per_day' => 80.00,
                'available_for_sale' => false,
                'status' => 'available',
                'condition' => 'excellent',
                'image_url' => 'https://images.unsplash.com/photo-1593941707882-a5bac6861d75?w=800&auto=format&fit=crop&q=60'
            ],
            [
                'make' => 'Chevrolet',
                'model' => 'Silverado 1500',
                'year' => 2024,
                'category' => 'pickup',
                'color' => 'Red',
                'license_plate' => 'SIL-2024',
                'mileage' => 15000,
                'fuel_type' => 'petrol',
                'transmission' => 'automatic',
                'description' => 'Powerful full-size pickup truck perfect for work and recreation.',
                'features' => ['bluetooth', 'backup_camera', 'cruise_control', 'keyless_entry', '4x4', 'tow_package', 'bed_liner', 'navigation'],
                'available_for_rent' => true,
                'rental_price_per_day' => 105.00,
                'self_drive_available' => true,
                'with_driver_available' => true,
                'driver_cost_per_day' => 85.00,
                'available_for_sale' => false,
                'status' => 'available',
                'condition' => 'excellent',
                'image_url' => 'https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?w=800&auto=format&fit=crop&q=60'
            ],
            [
                'make' => 'RAM',
                'model' => '1500',
                'year' => 2023,
                'category' => 'pickup',
                'color' => 'Black',
                'license_plate' => 'RAM-2023',
                'mileage' => 18000,
                'fuel_type' => 'petrol',
                'transmission' => 'automatic',
                'description' => 'Premium full-size pickup with luxury interior and smooth ride.',
                'features' => ['bluetooth', 'backup_camera', 'cruise_control', 'keyless_entry', '4x4', 'tow_package', 'bed_liner', 'leather_seats'],
                'available_for_rent' => true,
                'rental_price_per_day' => 110.00,
                'self_drive_available' => true,
                'with_driver_available' => true,
                'driver_cost_per_day' => 85.00,
                'available_for_sale' => false,
                'status' => 'available',
                'condition' => 'excellent',
                'image_url' => 'https://images.unsplash.com/photo-1609521263047-f8f205293f24?w=800&auto=format&fit=crop&q=60'
            ],

            // 🚐 VANS - All with proper van images
            [
                'make' => 'Toyota',
                'model' => 'Sienna',
                'year' => 2023,
                'category' => 'van',
                'color' => 'Silver',
                'license_plate' => 'SIE-2023',
                'mileage' => 20000,
                'fuel_type' => 'petrol',
                'transmission' => 'automatic',
                'description' => 'Spacious minivan perfect for large families and group transportation.',
                'features' => ['bluetooth', 'backup_camera', 'cruise_control', 'keyless_entry', 'all_wheel_drive', 'sliding_doors', 'third_row_seating'],
                'available_for_rent' => true,
                'rental_price_per_day' => 90.00,
                'self_drive_available' => true,
                'with_driver_available' => true,
                'driver_cost_per_day' => 75.00,
                'available_for_sale' => false,
                'status' => 'available',
                'condition' => 'excellent',
                'image_url' => 'https://images.unsplash.com/photo-1570125909232-eb263c188f7e?w=800&auto=format&fit=crop&q=60'
            ],
            [
                'make' => 'Honda',
                'model' => 'Odyssey',
                'year' => 2024,
                'category' => 'van',
                'color' => 'White',
                'license_plate' => 'ODY-2024',
                'mileage' => 10000,
                'fuel_type' => 'petrol',
                'transmission' => 'automatic',
                'description' => 'Premium minivan with advanced features and maximum comfort.',
                'features' => ['bluetooth', 'backup_camera', 'cruise_control', 'keyless_entry', 'sliding_doors', 'third_row_seating', 'entertainment_system'],
                'available_for_rent' => true,
                'rental_price_per_day' => 95.00,
                'self_drive_available' => true,
                'with_driver_available' => true,
                'driver_cost_per_day' => 75.00,
                'available_for_sale' => false,
                'status' => 'available',
                'condition' => 'excellent',
                'image_url' => 'https://images.unsplash.com/photo-1570125909517-53cb21c89ff2?w=800&auto=format&fit=crop&q=60'
            ],

            // 🏎️ LUXURY/SPORTS - All with proper luxury car images
            [
                'make' => 'BMW',
                'model' => '4 Series',
                'year' => 2024,
                'category' => 'luxury',
                'color' => 'Black',
                'license_plate' => 'BMW-2024',
                'mileage' => 5000,
                'fuel_type' => 'petrol',
                'transmission' => 'automatic',
                'description' => 'Luxury sports coupe with exceptional performance and premium features.',
                'features' => ['leather_seats', 'sunroof', 'navigation', 'bluetooth', 'backup_camera', 'heated_seats', 'premium_sound', 'sport_mode'],
                'available_for_rent' => true,
                'rental_price_per_day' => 180.00,
                'self_drive_available' => true,
                'with_driver_available' => true,
                'driver_cost_per_day' => 100.00,
                'available_for_sale' => false,
                'status' => 'available',
                'condition' => 'excellent',
                'image_url' => 'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800&auto=format&fit=crop&q=60'
            ],
            [
                'make' => 'Audi',
                'model' => 'A5',
                'year' => 2023,
                'category' => 'luxury',
                'color' => 'White',
                'license_plate' => 'AUD-2023',
                'mileage' => 12000,
                'fuel_type' => 'petrol',
                'transmission' => 'automatic',
                'description' => 'Premium coupe combining luxury, performance, and cutting-edge technology.',
                'features' => ['leather_seats', 'sunroof', 'navigation', 'bluetooth', 'backup_camera', 'heated_seats', 'premium_sound', 'all_wheel_drive'],
                'available_for_rent' => true,
                'rental_price_per_day' => 170.00,
                'self_drive_available' => true,
                'with_driver_available' => true,
                'driver_cost_per_day' => 95.00,
                'available_for_sale' => false,
                'status' => 'available',
                'condition' => 'excellent',
                'image_url' => 'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800&auto=format&fit=crop&q=60'
            ],
        ];

        foreach ($vehicles as $vehicleData) {
            $imageUrl = $vehicleData['image_url'];
            unset($vehicleData['image_url']);

            $vehicle = Vehicle::create($vehicleData);

            // Create a primary image for each vehicle
            VehicleImage::create([
                'vehicle_id' => $vehicle->id,
                'image_path' => $imageUrl,
                'is_primary' => true,
                'sort_order' => 1,
                'alt_text' => $vehicle->full_name,
            ]);
        }

        $this->command->info('✅ Successfully seeded 20 rental fleet vehicles with images!');
    }
}