<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Vehicle;
use App\Models\VehicleImage;

class SalesInventorySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $vehicles = [
            // 🚘 ECONOMY & COMPACT CARS
            [
                'make' => 'Toyota',
                'model' => 'Yaris',
                'year' => 2021,
                'category' => 'compact',
                'color' => 'White',
                'license_plate' => 'YAR-2021',
                'mileage' => 45000,
                'fuel_type' => 'petrol',
                'transmission' => 'automatic',
                'description' => 'Fuel-efficient compact car perfect for city driving and daily commuting.',
                'features' => ['bluetooth', 'backup_camera', 'cruise_control', 'keyless_entry', 'power_windows'],
                'available_for_rent' => false,
                'available_for_sale' => true,
                'sale_price' => 18500.00,
                'status' => 'available',
                'condition' => 'good',
                'image_url' => 'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800&q=80'
            ],
            [
                'make' => 'Kia',
                'model' => 'Rio',
                'year' => 2022,
                'category' => 'compact',
                'color' => 'Red',
                'license_plate' => 'RIO-2022',
                'mileage' => 35000,
                'fuel_type' => 'petrol',
                'transmission' => 'automatic',
                'description' => 'Stylish and affordable compact sedan with modern features.',
                'features' => ['bluetooth', 'backup_camera', 'cruise_control', 'keyless_entry', 'apple_carplay'],
                'available_for_rent' => false,
                'available_for_sale' => true,
                'sale_price' => 19800.00,
                'status' => 'available',
                'condition' => 'excellent',
                'image_url' => 'https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?w=800&q=80'
            ],
            [
                'make' => 'Chevrolet',
                'model' => 'Spark',
                'year' => 2021,
                'category' => 'compact',
                'color' => 'Blue',
                'license_plate' => 'SPK-2021',
                'mileage' => 42000,
                'fuel_type' => 'petrol',
                'transmission' => 'manual',
                'description' => 'Ultra-compact city car with excellent fuel economy and easy parking.',
                'features' => ['bluetooth', 'power_windows', 'air_conditioning', 'usb_ports'],
                'available_for_rent' => false,
                'available_for_sale' => true,
                'sale_price' => 15200.00,
                'status' => 'available',
                'condition' => 'good',
                'image_url' => 'https://images.unsplash.com/photo-1619767886558-efdc259cde1a?w=800&q=80'
            ],
            [
                'make' => 'Mitsubishi',
                'model' => 'Mirage',
                'year' => 2022,
                'category' => 'compact',
                'color' => 'Silver',
                'license_plate' => 'MIR-2022',
                'mileage' => 28000,
                'fuel_type' => 'petrol',
                'transmission' => 'automatic',
                'description' => 'Budget-friendly compact car with impressive fuel efficiency.',
                'features' => ['bluetooth', 'backup_camera', 'power_windows', 'air_conditioning'],
                'available_for_rent' => false,
                'available_for_sale' => true,
                'sale_price' => 16900.00,
                'status' => 'available',
                'condition' => 'excellent',
                'image_url' => 'https://images.unsplash.com/photo-1623869675781-80aa31012a5a?w=800&q=80'
            ],
            [
                'make' => 'Suzuki',
                'model' => 'Swift',
                'year' => 2021,
                'category' => 'compact',
                'color' => 'Yellow',
                'license_plate' => 'SWF-2021',
                'mileage' => 38000,
                'fuel_type' => 'petrol',
                'transmission' => 'manual',
                'description' => 'Sporty compact hatchback with agile handling and modern design.',
                'features' => ['bluetooth', 'cruise_control', 'keyless_entry', 'power_windows', 'alloy_wheels'],
                'available_for_rent' => false,
                'available_for_sale' => true,
                'sale_price' => 17500.00,
                'status' => 'available',
                'condition' => 'good',
                'image_url' => 'https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=800&q=80'
            ],
            [
                'make' => 'Volkswagen',
                'model' => 'Polo',
                'year' => 2022,
                'category' => 'compact',
                'color' => 'Gray',
                'license_plate' => 'POL-2022',
                'mileage' => 32000,
                'fuel_type' => 'petrol',
                'transmission' => 'automatic',
                'description' => 'Premium compact car with German engineering and quality interior.',
                'features' => ['bluetooth', 'backup_camera', 'cruise_control', 'keyless_entry', 'heated_seats'],
                'available_for_rent' => false,
                'available_for_sale' => true,
                'sale_price' => 21200.00,
                'status' => 'available',
                'condition' => 'excellent',
                'image_url' => 'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800&q=80'
            ],

            // 🚘 SEDANS (NON-RENTAL MODELS)
            [
                'make' => 'Hyundai',
                'model' => 'Sonata',
                'year' => 2021,
                'category' => 'sedan',
                'color' => 'Black',
                'license_plate' => 'SON-2021',
                'mileage' => 48000,
                'fuel_type' => 'petrol',
                'transmission' => 'automatic',
                'description' => 'Midsize sedan with bold styling and advanced safety features.',
                'features' => ['bluetooth', 'backup_camera', 'cruise_control', 'keyless_entry', 'blind_spot_monitoring', 'heated_seats'],
                'available_for_rent' => false,
                'available_for_sale' => true,
                'sale_price' => 24800.00,
                'status' => 'available',
                'condition' => 'good',
                'image_url' => 'https://images.unsplash.com/photo-1563720223185-11003d516935?w=800&q=80'
            ],
            [
                'make' => 'Kia',
                'model' => 'Forte',
                'year' => 2022,
                'category' => 'sedan',
                'color' => 'White',
                'license_plate' => 'FOR-2022',
                'mileage' => 25000,
                'fuel_type' => 'petrol',
                'transmission' => 'automatic',
                'description' => 'Compact sedan with spacious interior and excellent warranty coverage.',
                'features' => ['bluetooth', 'backup_camera', 'cruise_control', 'keyless_entry', 'apple_carplay', 'wireless_charging'],
                'available_for_rent' => false,
                'available_for_sale' => true,
                'sale_price' => 22500.00,
                'status' => 'available',
                'condition' => 'excellent',
                'image_url' => 'https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=800&q=80'
            ],
            [
                'make' => 'Mazda',
                'model' => '6',
                'year' => 2021,
                'category' => 'sedan',
                'color' => 'Red',
                'license_plate' => 'MAZ-2021',
                'mileage' => 41000,
                'fuel_type' => 'petrol',
                'transmission' => 'automatic',
                'description' => 'Premium midsize sedan with sporty handling and upscale interior.',
                'features' => ['bluetooth', 'backup_camera', 'cruise_control', 'keyless_entry', 'leather_seats', 'sunroof', 'navigation'],
                'available_for_rent' => false,
                'available_for_sale' => true,
                'sale_price' => 26900.00,
                'status' => 'available',
                'condition' => 'good',
                'image_url' => 'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800&q=80'
            ],
            [
                'make' => 'Subaru',
                'model' => 'Impreza',
                'year' => 2022,
                'category' => 'sedan',
                'color' => 'Blue',
                'license_plate' => 'IMP-2022',
                'mileage' => 30000,
                'fuel_type' => 'petrol',
                'transmission' => 'automatic',
                'description' => 'All-wheel drive sedan with excellent safety ratings and reliability.',
                'features' => ['bluetooth', 'backup_camera', 'cruise_control', 'keyless_entry', 'all_wheel_drive', 'eyesight_safety'],
                'available_for_rent' => false,
                'available_for_sale' => true,
                'sale_price' => 23800.00,
                'status' => 'available',
                'condition' => 'excellent',
                'image_url' => 'https://images.unsplash.com/photo-1619767886558-efdc259cde1a?w=800&q=80'
            ],
            [
                'make' => 'Volkswagen',
                'model' => 'Passat',
                'year' => 2021,
                'category' => 'sedan',
                'color' => 'Silver',
                'license_plate' => 'PAS-2021',
                'mileage' => 44000,
                'fuel_type' => 'petrol',
                'transmission' => 'automatic',
                'description' => 'European luxury sedan with refined driving experience and premium features.',
                'features' => ['bluetooth', 'backup_camera', 'cruise_control', 'keyless_entry', 'leather_seats', 'heated_seats', 'navigation'],
                'available_for_rent' => false,
                'available_for_sale' => true,
                'sale_price' => 28500.00,
                'status' => 'available',
                'condition' => 'good',
                'image_url' => 'https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?w=800&q=80'
            ],
            [
                'make' => 'Skoda',
                'model' => 'Octavia',
                'year' => 2022,
                'category' => 'sedan',
                'color' => 'Green',
                'license_plate' => 'OCT-2022',
                'mileage' => 22000,
                'fuel_type' => 'petrol',
                'transmission' => 'automatic',
                'description' => 'Practical family sedan with spacious interior and advanced technology.',
                'features' => ['bluetooth', 'backup_camera', 'cruise_control', 'keyless_entry', 'navigation', 'panoramic_sunroof'],
                'available_for_rent' => false,
                'available_for_sale' => true,
                'sale_price' => 25200.00,
                'status' => 'available',
                'condition' => 'excellent',
                'image_url' => 'https://images.unsplash.com/photo-1623869675781-80aa31012a5a?w=800&q=80'
            ],

            // 🚙 SUVs & CROSSOVERS
            [
                'make' => 'Mazda',
                'model' => 'CX-5',
                'year' => 2022,
                'category' => 'suv',
                'color' => 'Red',
                'license_plate' => 'CX5-2022',
                'mileage' => 28000,
                'fuel_type' => 'petrol',
                'transmission' => 'automatic',
                'description' => 'Stylish compact SUV with premium interior and excellent driving dynamics.',
                'features' => ['bluetooth', 'backup_camera', 'cruise_control', 'keyless_entry', 'all_wheel_drive', 'leather_seats', 'navigation'],
                'available_for_rent' => false,
                'available_for_sale' => true,
                'sale_price' => 32500.00,
                'status' => 'available',
                'condition' => 'excellent',
                'image_url' => 'https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=800&q=80'
            ],
            [
                'make' => 'Nissan',
                'model' => 'Pathfinder',
                'year' => 2021,
                'category' => 'suv',
                'color' => 'Black',
                'license_plate' => 'PTH-2021',
                'mileage' => 52000,
                'fuel_type' => 'petrol',
                'transmission' => 'automatic',
                'description' => 'Three-row family SUV with spacious interior and advanced safety features.',
                'features' => ['bluetooth', 'backup_camera', 'cruise_control', 'keyless_entry', 'all_wheel_drive', 'third_row_seating', 'navigation'],
                'available_for_rent' => false,
                'available_for_sale' => true,
                'sale_price' => 35800.00,
                'status' => 'available',
                'condition' => 'good',
                'image_url' => 'https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=800&q=80'
            ],
            [
                'make' => 'Mitsubishi',
                'model' => 'Outlander',
                'year' => 2022,
                'category' => 'suv',
                'color' => 'White',
                'license_plate' => 'OUT-2022',
                'mileage' => 24000,
                'fuel_type' => 'petrol',
                'transmission' => 'automatic',
                'description' => 'Versatile midsize SUV with third-row seating and comprehensive warranty.',
                'features' => ['bluetooth', 'backup_camera', 'cruise_control', 'keyless_entry', 'all_wheel_drive', 'third_row_seating'],
                'available_for_rent' => false,
                'available_for_sale' => true,
                'sale_price' => 29800.00,
                'status' => 'available',
                'condition' => 'excellent',
                'image_url' => 'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800&q=80'
            ],
            [
                'make' => 'Peugeot',
                'model' => '3008',
                'year' => 2021,
                'category' => 'suv',
                'color' => 'Gray',
                'license_plate' => 'PEU-2021',
                'mileage' => 46000,
                'fuel_type' => 'petrol',
                'transmission' => 'automatic',
                'description' => 'French compact SUV with distinctive design and premium interior.',
                'features' => ['bluetooth', 'backup_camera', 'cruise_control', 'keyless_entry', 'panoramic_sunroof', 'navigation'],
                'available_for_rent' => false,
                'available_for_sale' => true,
                'sale_price' => 31200.00,
                'status' => 'available',
                'condition' => 'good',
                'image_url' => 'https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=800&q=80'
            ],
            [
                'make' => 'Renault',
                'model' => 'Duster',
                'year' => 2022,
                'category' => 'suv',
                'color' => 'Orange',
                'license_plate' => 'DUS-2022',
                'mileage' => 26000,
                'fuel_type' => 'petrol',
                'transmission' => 'manual',
                'description' => 'Rugged and affordable compact SUV perfect for adventure and daily use.',
                'features' => ['bluetooth', 'backup_camera', 'cruise_control', 'keyless_entry', 'all_wheel_drive', 'roof_rails'],
                'available_for_rent' => false,
                'available_for_sale' => true,
                'sale_price' => 24500.00,
                'status' => 'available',
                'condition' => 'excellent',
                'image_url' => 'https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=800&q=80'
            ],
            [
                'make' => 'Chevrolet',
                'model' => 'Traverse',
                'year' => 2021,
                'category' => 'suv',
                'color' => 'Blue',
                'license_plate' => 'TRV-2021',
                'mileage' => 49000,
                'fuel_type' => 'petrol',
                'transmission' => 'automatic',
                'description' => 'Full-size three-row SUV with spacious interior and family-friendly features.',
                'features' => ['bluetooth', 'backup_camera', 'cruise_control', 'keyless_entry', 'all_wheel_drive', 'third_row_seating', 'navigation'],
                'available_for_rent' => false,
                'available_for_sale' => true,
                'sale_price' => 33800.00,
                'status' => 'available',
                'condition' => 'good',
                'image_url' => 'https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=800&q=80'
            ],
            [
                'make' => 'Lexus',
                'model' => 'RX 350',
                'year' => 2022,
                'category' => 'luxury',
                'color' => 'Pearl White',
                'license_plate' => 'LEX-2022',
                'mileage' => 18000,
                'fuel_type' => 'petrol',
                'transmission' => 'automatic',
                'description' => 'Luxury midsize SUV with exceptional comfort and reliability.',
                'features' => ['leather_seats', 'sunroof', 'navigation', 'bluetooth', 'backup_camera', 'heated_seats', 'premium_sound', 'all_wheel_drive'],
                'available_for_rent' => false,
                'available_for_sale' => true,
                'sale_price' => 52800.00,
                'status' => 'available',
                'condition' => 'excellent',
                'image_url' => 'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800&q=80'
            ],

            // 🛻 PICKUPS & UTILITY
            [
                'make' => 'Toyota',
                'model' => 'Hilux',
                'year' => 2022,
                'category' => 'pickup',
                'color' => 'White',
                'license_plate' => 'HIL-2022',
                'mileage' => 35000,
                'fuel_type' => 'diesel',
                'transmission' => 'automatic',
                'description' => 'Legendary pickup truck with unmatched durability and off-road capability.',
                'features' => ['bluetooth', 'backup_camera', 'cruise_control', 'keyless_entry', '4x4', 'tow_package', 'bed_liner'],
                'available_for_rent' => false,
                'available_for_sale' => true,
                'sale_price' => 38500.00,
                'status' => 'available',
                'condition' => 'excellent',
                'image_url' => 'https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=800&q=80'
            ],
            [
                'make' => 'Isuzu',
                'model' => 'D-Max',
                'year' => 2021,
                'category' => 'pickup',
                'color' => 'Silver',
                'license_plate' => 'DMX-2021',
                'mileage' => 42000,
                'fuel_type' => 'diesel',
                'transmission' => 'manual',
                'description' => 'Robust pickup truck designed for work and adventure with excellent payload.',
                'features' => ['bluetooth', 'backup_camera', 'cruise_control', 'keyless_entry', '4x4', 'tow_package', 'bed_liner'],
                'available_for_rent' => false,
                'available_for_sale' => true,
                'sale_price' => 34200.00,
                'status' => 'available',
                'condition' => 'good',
                'image_url' => 'https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=800&q=80'
            ],
            [
                'make' => 'Nissan',
                'model' => 'Navara',
                'year' => 2022,
                'category' => 'pickup',
                'color' => 'Black',
                'license_plate' => 'NAV-2022',
                'mileage' => 28000,
                'fuel_type' => 'diesel',
                'transmission' => 'automatic',
                'description' => 'Modern pickup truck with car-like comfort and truck-like capability.',
                'features' => ['bluetooth', 'backup_camera', 'cruise_control', 'keyless_entry', '4x4', 'tow_package', 'bed_liner', 'navigation'],
                'available_for_rent' => false,
                'available_for_sale' => true,
                'sale_price' => 36800.00,
                'status' => 'available',
                'condition' => 'excellent',
                'image_url' => 'https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=800&q=80'
            ],
            [
                'make' => 'Ford',
                'model' => 'Ranger Raptor',
                'year' => 2021,
                'category' => 'pickup',
                'color' => 'Orange',
                'license_plate' => 'RAP-2021',
                'mileage' => 38000,
                'fuel_type' => 'diesel',
                'transmission' => 'automatic',
                'description' => 'High-performance off-road pickup truck with racing-inspired features.',
                'features' => ['bluetooth', 'backup_camera', 'cruise_control', 'keyless_entry', '4x4', 'off_road_tires', 'sport_mode', 'navigation'],
                'available_for_rent' => false,
                'available_for_sale' => true,
                'sale_price' => 45200.00,
                'status' => 'available',
                'condition' => 'good',
                'image_url' => 'https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=800&q=80'
            ],

            // 🚐 VANS & MPVs
            [
                'make' => 'Volkswagen',
                'model' => 'Transporter',
                'year' => 2022,
                'category' => 'van',
                'color' => 'White',
                'license_plate' => 'TRP-2022',
                'mileage' => 32000,
                'fuel_type' => 'diesel',
                'transmission' => 'manual',
                'description' => 'Versatile commercial van perfect for business and cargo transportation.',
                'features' => ['bluetooth', 'backup_camera', 'cruise_control', 'power_windows', 'cargo_area'],
                'available_for_rent' => false,
                'available_for_sale' => true,
                'sale_price' => 42500.00,
                'status' => 'available',
                'condition' => 'excellent',
                'image_url' => 'https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=800&q=80'
            ],
            [
                'make' => 'Mercedes-Benz',
                'model' => 'Vito',
                'year' => 2021,
                'category' => 'van',
                'color' => 'Silver',
                'license_plate' => 'VIT-2021',
                'mileage' => 45000,
                'fuel_type' => 'diesel',
                'transmission' => 'automatic',
                'description' => 'Premium commercial van with luxury features and excellent build quality.',
                'features' => ['bluetooth', 'backup_camera', 'cruise_control', 'keyless_entry', 'navigation', 'premium_interior'],
                'available_for_rent' => false,
                'available_for_sale' => true,
                'sale_price' => 48800.00,
                'status' => 'available',
                'condition' => 'good',
                'image_url' => 'https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=800&q=80'
            ],
            [
                'make' => 'Toyota',
                'model' => 'HiAce',
                'year' => 2022,
                'category' => 'van',
                'color' => 'White',
                'license_plate' => 'HIA-2022',
                'mileage' => 28000,
                'fuel_type' => 'diesel',
                'transmission' => 'manual',
                'description' => 'Reliable passenger and cargo van with excellent fuel economy and durability.',
                'features' => ['bluetooth', 'backup_camera', 'air_conditioning', 'power_windows', 'sliding_doors'],
                'available_for_rent' => false,
                'available_for_sale' => true,
                'sale_price' => 38900.00,
                'status' => 'available',
                'condition' => 'excellent',
                'image_url' => 'https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=800&q=80'
            ],

            // 🏎️ LUXURY / SPORTS / PREMIUM
            [
                'make' => 'BMW',
                'model' => 'X6',
                'year' => 2022,
                'category' => 'luxury',
                'color' => 'Black',
                'license_plate' => 'BMX-2022',
                'mileage' => 15000,
                'fuel_type' => 'petrol',
                'transmission' => 'automatic',
                'description' => 'Luxury sports SUV with coupe styling and exceptional performance.',
                'features' => ['leather_seats', 'sunroof', 'navigation', 'bluetooth', 'backup_camera', 'heated_seats', 'premium_sound', 'all_wheel_drive', 'sport_mode'],
                'available_for_rent' => false,
                'available_for_sale' => true,
                'sale_price' => 78500.00,
                'status' => 'available',
                'condition' => 'excellent',
                'image_url' => 'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800&q=80'
            ],
            [
                'make' => 'Audi',
                'model' => 'Q8',
                'year' => 2021,
                'category' => 'luxury',
                'color' => 'Gray',
                'license_plate' => 'AUQ-2021',
                'mileage' => 22000,
                'fuel_type' => 'petrol',
                'transmission' => 'automatic',
                'description' => 'Flagship luxury SUV with cutting-edge technology and premium comfort.',
                'features' => ['leather_seats', 'sunroof', 'navigation', 'bluetooth', 'backup_camera', 'heated_seats', 'premium_sound', 'all_wheel_drive', 'virtual_cockpit'],
                'available_for_rent' => false,
                'available_for_sale' => true,
                'sale_price' => 72800.00,
                'status' => 'available',
                'condition' => 'excellent',
                'image_url' => 'https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=800&q=80'
            ],
            [
                'make' => 'Lexus',
                'model' => 'LC 500',
                'year' => 2022,
                'category' => 'luxury',
                'color' => 'Red',
                'license_plate' => 'LC5-2022',
                'mileage' => 8000,
                'fuel_type' => 'petrol',
                'transmission' => 'automatic',
                'description' => 'Stunning luxury coupe with breathtaking design and exhilarating performance.',
                'features' => ['leather_seats', 'sunroof', 'navigation', 'bluetooth', 'backup_camera', 'heated_seats', 'premium_sound', 'sport_mode', 'adaptive_suspension'],
                'available_for_rent' => false,
                'available_for_sale' => true,
                'sale_price' => 89500.00,
                'status' => 'available',
                'condition' => 'excellent',
                'image_url' => 'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800&q=80'
            ],
            [
                'make' => 'Jaguar',
                'model' => 'F-Type',
                'year' => 2021,
                'category' => 'luxury',
                'color' => 'British Racing Green',
                'license_plate' => 'JAG-2021',
                'mileage' => 12000,
                'fuel_type' => 'petrol',
                'transmission' => 'automatic',
                'description' => 'Iconic British sports car with stunning design and thrilling performance.',
                'features' => ['leather_seats', 'sunroof', 'navigation', 'bluetooth', 'backup_camera', 'heated_seats', 'premium_sound', 'sport_mode', 'performance_exhaust'],
                'available_for_rent' => false,
                'available_for_sale' => true,
                'sale_price' => 82200.00,
                'status' => 'available',
                'condition' => 'excellent',
                'image_url' => 'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800&q=80'
            ],
        ];

        foreach ($vehicles as $vehicleData) {
            $imageUrl = $vehicleData['image_url'];
            unset($vehicleData['image_url']);

            $vehicle = Vehicle::create($vehicleData);

            // Create a primary image for each vehicle
            VehicleImage::create([
                'vehicle_id' => $vehicle->id,
                'image_path' => $imageUrl,
                'is_primary' => true,
                'sort_order' => 1,
                'alt_text' => $vehicle->full_name,
            ]);
        }

        $this->command->info('✅ Successfully seeded 30 sales inventory vehicles with images!');
    }
}