<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Vehicle;

class VehicleSeeder extends Seeder
{
    public function run(): void
    {
        $vehicles = [
            // Rental Vehicles
            [
                'make' => 'Toyota',
                'model' => 'Camry',
                'year' => 2023,
                'color' => 'Silver',
                'license_plate' => 'AA-12345',
                'mileage' => 15000,
                'fuel_type' => 'petrol',
                'transmission' => 'automatic',
                'category' => 'sedan',
                'description' => 'Comfortable and reliable sedan perfect for business trips and family outings.',
                'features' => ['AC', 'GPS', 'Bluetooth', 'Backup Camera', 'Cruise Control'],
                'available_for_rent' => true,
                'rental_price_per_day' => 45.00,
                'self_drive_available' => true,
                'with_driver_available' => true,
                'driver_cost_per_day' => 25.00,
                'available_for_sale' => false,
                'status' => 'available',
            ],
            [
                'make' => 'Honda',
                'model' => 'CR-V',
                'year' => 2022,
                'color' => 'Black',
                'license_plate' => 'AA-23456',
                'mileage' => 25000,
                'fuel_type' => 'petrol',
                'transmission' => 'automatic',
                'category' => 'suv',
                'description' => 'Spacious SUV ideal for family trips and outdoor adventures.',
                'features' => ['AC', 'GPS', 'Bluetooth', '4WD', 'Sunroof', 'Leather Seats'],
                'available_for_rent' => true,
                'rental_price_per_day' => 65.00,
                'self_drive_available' => true,
                'with_driver_available' => true,
                'driver_cost_per_day' => 30.00,
                'available_for_sale' => false,
                'status' => 'available',
            ],
            [
                'make' => 'Ford',
                'model' => 'F-150',
                'year' => 2023,
                'color' => 'Blue',
                'license_plate' => 'AA-34567',
                'mileage' => 10000,
                'fuel_type' => 'diesel',
                'transmission' => 'automatic',
                'category' => 'pickup',
                'description' => 'Powerful pickup truck perfect for heavy-duty tasks and cargo transport.',
                'features' => ['AC', 'GPS', '4WD', 'Towing Package', 'Bed Liner'],
                'available_for_rent' => true,
                'rental_price_per_day' => 75.00,
                'self_drive_available' => true,
                'with_driver_available' => true,
                'driver_cost_per_day' => 35.00,
                'available_for_sale' => false,
                'status' => 'available',
            ],
            [
                'make' => 'Mercedes-Benz',
                'model' => 'E-Class',
                'year' => 2024,
                'color' => 'White',
                'license_plate' => 'AA-45678',
                'mileage' => 5000,
                'fuel_type' => 'petrol',
                'transmission' => 'automatic',
                'category' => 'luxury',
                'description' => 'Premium luxury sedan for special occasions and executive travel.',
                'features' => ['AC', 'GPS', 'Bluetooth', 'Leather Seats', 'Sunroof', 'Premium Sound System', 'Heated Seats'],
                'available_for_rent' => true,
                'rental_price_per_day' => 120.00,
                'self_drive_available' => false,
                'with_driver_available' => true,
                'driver_cost_per_day' => 50.00,
                'available_for_sale' => false,
                'status' => 'available',
            ],
            [
                'make' => 'Hyundai',
                'model' => 'Accent',
                'year' => 2022,
                'color' => 'Red',
                'license_plate' => 'AA-56789',
                'mileage' => 30000,
                'fuel_type' => 'petrol',
                'transmission' => 'manual',
                'category' => 'compact',
                'description' => 'Economical compact car perfect for city driving.',
                'features' => ['AC', 'Bluetooth', 'USB Port'],
                'available_for_rent' => true,
                'rental_price_per_day' => 30.00,
                'self_drive_available' => true,
                'with_driver_available' => false,
                'available_for_sale' => false,
                'status' => 'available',
            ],

            // Vehicles for Sale
            [
                'make' => 'Toyota',
                'model' => 'Land Cruiser',
                'year' => 2020,
                'color' => 'White',
                'license_plate' => 'AA-67890',
                'mileage' => 45000,
                'fuel_type' => 'diesel',
                'transmission' => 'automatic',
                'category' => 'suv',
                'description' => 'Well-maintained Land Cruiser with full service history. Perfect for Ethiopian terrain.',
                'features' => ['AC', 'GPS', '4WD', 'Leather Seats', 'Sunroof', 'Premium Sound System'],
                'available_for_rent' => false,
                'available_for_sale' => true,
                'sale_price' => 45000.00,
                'condition' => 'excellent',
                'is_sold' => false,
                'status' => 'available',
            ],
            [
                'make' => 'Honda',
                'model' => 'Civic',
                'year' => 2019,
                'color' => 'Gray',
                'license_plate' => 'AA-78901',
                'mileage' => 55000,
                'fuel_type' => 'petrol',
                'transmission' => 'automatic',
                'category' => 'sedan',
                'description' => 'Reliable Honda Civic in great condition. Single owner, regularly serviced.',
                'features' => ['AC', 'GPS', 'Bluetooth', 'Backup Camera', 'Alloy Wheels'],
                'available_for_rent' => false,
                'available_for_sale' => true,
                'sale_price' => 18000.00,
                'condition' => 'good',
                'is_sold' => false,
                'status' => 'available',
            ],
            [
                'make' => 'Nissan',
                'model' => 'Patrol',
                'year' => 2021,
                'color' => 'Black',
                'license_plate' => 'AA-89012',
                'mileage' => 35000,
                'fuel_type' => 'diesel',
                'transmission' => 'automatic',
                'category' => 'suv',
                'description' => 'Powerful Nissan Patrol with low mileage. Excellent for long-distance travel.',
                'features' => ['AC', 'GPS', '4WD', 'Leather Seats', 'Sunroof', '7 Seats'],
                'available_for_rent' => false,
                'available_for_sale' => true,
                'sale_price' => 52000.00,
                'condition' => 'excellent',
                'is_sold' => false,
                'status' => 'available',
            ],

            // Dual Purpose (Rent & Sale)
            [
                'make' => 'Toyota',
                'model' => 'Corolla',
                'year' => 2021,
                'color' => 'Silver',
                'license_plate' => 'AA-90123',
                'mileage' => 40000,
                'fuel_type' => 'petrol',
                'transmission' => 'automatic',
                'category' => 'sedan',
                'description' => 'Popular Toyota Corolla available for rent or purchase.',
                'features' => ['AC', 'GPS', 'Bluetooth', 'Backup Camera'],
                'available_for_rent' => true,
                'rental_price_per_day' => 40.00,
                'self_drive_available' => true,
                'with_driver_available' => true,
                'driver_cost_per_day' => 20.00,
                'available_for_sale' => true,
                'sale_price' => 22000.00,
                'condition' => 'good',
                'is_sold' => false,
                'status' => 'available',
            ],
            [
                'make' => 'Suzuki',
                'model' => 'Vitara',
                'year' => 2022,
                'color' => 'Blue',
                'license_plate' => 'AA-01234',
                'mileage' => 20000,
                'fuel_type' => 'petrol',
                'transmission' => 'automatic',
                'category' => 'suv',
                'description' => 'Compact SUV perfect for city and off-road adventures.',
                'features' => ['AC', 'GPS', 'Bluetooth', '4WD', 'Alloy Wheels'],
                'available_for_rent' => true,
                'rental_price_per_day' => 55.00,
                'self_drive_available' => true,
                'with_driver_available' => true,
                'driver_cost_per_day' => 25.00,
                'available_for_sale' => true,
                'sale_price' => 28000.00,
                'condition' => 'excellent',
                'is_sold' => false,
                'status' => 'available',
            ],
        ];

        foreach ($vehicles as $vehicle) {
            Vehicle::create($vehicle);
        }
    }
}